name: Deploy to render

on:
  workflow_run:
    workflows: ["Retrain model on new commit"]
    types: [completed]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github_actions
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: checkout code
        uses: actions/checkout@v3
      
      - name: set up python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: install required packages
        run: |
          pip install kaggle python-dotenv
      
      - name: download latest model
        env:
          KAGGLE_USERNAME: ${{ secrets.KAGGLE_USERNAME }}
          KAGGLE_KEY: ${{ secrets.KAGGLE_KEY }}
        run: |
          python scripts/download_model.py
      
      - name: verify model download
        run: |
          if [ -f "./models/word2vec.pkl" ] && [ -f "./models/model.pkl" ]; then
            echo "Model downloaded successfully"
            ls -la ./models
          else
            echo "Model download failed"
            exit 1
          fi
      
      - name: commit and push model files
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add .
          git commit -m "Add retrained models"
          git push https://$GH_PAT@github.com/parbhat-cpp/suicidal-ml.git HEAD:main
